#!/usr/bin/env python3
"""Generate a Silkscreen GFXfont (LovyanGFX / Adafruit GFX layout) at a given pixel size.

Rasterized with FreeType's monochrome renderer (no anti-aliasing), ASCII 0x20-0x7E.
Silkscreen is drawn on an 8px grid: 8/16/24px are pixel-perfect, other sizes (e.g. 12px)
come out with some 1px and some 2px strokes -- chunkier, but readable.

Silkscreen Regular is OFL (google/fonts, ofl/silkscreen). Get the TTF with:
    curl -L -o Silkscreen-Regular.ttf https://github.com/google/fonts/raw/main/ofl/silkscreen/Silkscreen-Regular.ttf

10px is special: FreeType's 10px render is broken (letters with gaps), so it is built from the
pixel-perfect 8px glyphs instead, stretched from 5 to 7 cap rows by doubling cap rows 1 and 3.
That keeps every stroke exactly 1px -- a classic 5x7 console font in Silkscreen's shapes.

Usage:
    tools/.venv/bin/pip install freetype-py
    tools/.venv/bin/python tools/gen_silkscreen_font.py Silkscreen-Regular.ttf 10 src/fonts/ui_font_silkscreen_10.cpp
"""
import sys

import freetype

# 10px mode: 8px cap rows (0 = cap top) -> output cap rows. Rows outside the cap box shift by
# the 2 added rows below it, and stay put above it.
STRETCH_ROWS = {0: [0], 1: [1, 2], 2: [3], 3: [4, 5], 4: [6]}
CAP_8 = 5


def stretched_rows(rows, top):
    """rows: list of pixel rows (top to bottom) whose first row sits `top` px above the baseline."""
    out = {}
    for y, row in enumerate(rows):
        r = CAP_8 - top + y  # 8px cap-row index
        targets = STRETCH_ROWS.get(r, [r if r < 0 else r + 2])
        for t in targets:
            out[t] = row
    if not out:
        return [], top
    ks = sorted(out)
    return [out[k] for k in range(ks[0], ks[-1] + 1)], (CAP_8 + 2) - ks[0]


def main():
    ttf, px, out_path = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    name = "ui_font_silkscreen_%d_regular" % px
    face = freetype.Face(ttf)
    stretch = px == 10
    face.set_pixel_sizes(0, 8 if stretch else px)
    flags = freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO | freetype.FT_LOAD_MONOCHROME

    bitmap = bytearray()
    glyphs = []
    for code in range(0x20, 0x7F):
        face.load_char(chr(code), flags)
        g = face.glyph
        bm = g.bitmap
        # GFX packing: one continuous MSB-first bitstream per glyph, byte-aligned at its start.
        rows = [[1 if bm.buffer[y * bm.pitch + x // 8] & (0x80 >> (x % 8)) else 0 for x in range(bm.width)]
                for y in range(bm.rows)]
        top = g.bitmap_top
        if stretch:
            rows, top = stretched_rows(rows, top)
        bits = [b for row in rows for b in row]
        offset = len(bitmap)
        for i in range(0, len(bits), 8):
            byte = 0
            for j, b in enumerate(bits[i:i + 8]):
                byte |= b << (7 - j)
            bitmap.append(byte)
        glyphs.append((offset, bm.width if rows else 0, len(rows), g.advance.x >> 6, g.bitmap_left, -top, chr(code)))

    y_advance = (face.size.height >> 6) + (2 if stretch else 0)
    lines = [
        "// GENERATED by tools/gen_silkscreen_font.py (%dpx) -- do not edit by hand." % px,
        "// Silkscreen Regular (OFL, google/fonts ofl/silkscreen), ASCII 0x20-0x7E, FreeType mono%s."
        % (" at 8px, cap rows 1 and 3 doubled" if stretch else ""),
        '#include "ui_font_silkscreen.h"',
        "",
        "static const uint8_t %s_bitmaps[] = {" % name,
    ]
    for i in range(0, len(bitmap), 16):
        lines.append("    " + ", ".join("0x%02X" % b for b in bitmap[i:i + 16]) + ",")
    lines.append("};")
    lines.append("")
    lines.append("static const lgfx::GFXglyph %s_glyphs[] = {" % name)
    for off, w, h, adv, xo, yo, ch in glyphs:
        label = "backslash" if ch == "\\" else ch
        lines.append("    { %5d, %3d, %3d, %3d, %3d, %4d }, // 0x%02X %s" % (off, w, h, adv, xo, yo, ord(ch), label))
    lines.append("};")
    lines.append("")
    lines.append("const lgfx::GFXfont %s = { (uint8_t *)%s_bitmaps, (lgfx::GFXglyph *)%s_glyphs, 0x20, 0x7E, %d };"
                 % (name, name, name, y_advance))
    open(out_path, "w").write("\n".join(lines) + "\n")
    a = glyphs[ord("A") - 0x20]
    print("wrote %s: %d bytes of bitmap, 'A' is %dx%d (cap height %d), line height %d"
          % (out_path, len(bitmap), a[1], a[2], -a[5], y_advance))


if __name__ == "__main__":
    main()
