#!/usr/bin/env python3
"""Convert a pixel-art PNG into a C array for the firmware (app profile icons).

Output is RGB565 big-endian bytes -- the same format as the HID icon upload (icon_store.h)
and what ui::image565() draws. Transparent pixels become black (the UI background, which
image565 skips). No resampling: draw the PNG at the exact size you want on the device.

Usage:
    tools/.venv/bin/python tools/gen_icon_c.py tools/icons/figma_pixel_24.png \
        app_icon_figma_24 src/app_profiles/icons/figma_24.c
"""
import sys

from PIL import Image


def main():
    png, name, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    img = Image.open(png).convert("RGBA")
    w, h = img.size
    data = bytearray()
    for r, g, b, a in img.getdata():
        if a < 128:
            r = g = b = 0
        v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        data += bytes((v >> 8, v & 0xFF))
    lines = [
        "// GENERATED by tools/gen_icon_c.py from %s -- do not edit by hand." % png.split("/")[-1],
        "// %dx%d, RGB565 big-endian (ui::image565 / icon_store format)." % (w, h),
        '#include "app_icons.h"',
        "",
        "const uint8_t %s[%d] = {" % (name, len(data)),
    ]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",")
    lines.append("};")
    open(out_path, "w").write("\n".join(lines) + "\n")
    print("wrote %s: %dx%d, %d bytes" % (out_path, w, h, len(data)))


if __name__ == "__main__":
    main()
