// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

// void ui_IdleAnim_screen_init(void)
// {
// ui_IdleAnim = lv_obj_create(NULL);
// lv_obj_clear_flag( ui_IdleAnim, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
// lv_obj_set_style_bg_color(ui_IdleAnim, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
// lv_obj_set_style_bg_opa(ui_IdleAnim, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

// ui_IdleCat = lv_label_create(ui_IdleAnim);
// lv_obj_set_width( ui_IdleCat, LV_SIZE_CONTENT);  /// 1
// lv_obj_set_height( ui_IdleCat, LV_SIZE_CONTENT);   /// 1
// lv_obj_set_align( ui_IdleCat, LV_ALIGN_CENTER );
// lv_label_set_text(ui_IdleCat,"A");
// lv_obj_set_style_text_color(ui_IdleCat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
// lv_obj_set_style_text_opa(ui_IdleCat, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_text_font(ui_IdleCat, &ui_font_IdleCat, LV_PART_MAIN| LV_STATE_DEFAULT);

// ui_IdleCatShadow = lv_label_create(ui_IdleAnim);
// lv_obj_set_width( ui_IdleCatShadow, LV_SIZE_CONTENT);  /// 1
// lv_obj_set_height( ui_IdleCatShadow, LV_SIZE_CONTENT);   /// 1
// lv_obj_set_align( ui_IdleCatShadow, LV_ALIGN_CENTER );
// lv_label_set_text(ui_IdleCatShadow,"E");
// lv_obj_set_style_text_color(ui_IdleCatShadow, lv_color_hex(0x9C9C9C), LV_PART_MAIN | LV_STATE_DEFAULT );
// lv_obj_set_style_text_opa(ui_IdleCatShadow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_text_font(ui_IdleCatShadow, &ui_font_IdleCat, LV_PART_MAIN| LV_STATE_DEFAULT);

// ui_IdleQuote = lv_label_create(ui_IdleAnim);
// lv_obj_set_width( ui_IdleQuote, LV_SIZE_CONTENT);  /// 1
// lv_obj_set_height( ui_IdleQuote, LV_SIZE_CONTENT);   /// 1
// lv_obj_set_x( ui_IdleQuote, 0 );
// lv_obj_set_y( ui_IdleQuote, 55 );
// lv_obj_set_align( ui_IdleQuote, LV_ALIGN_CENTER );
// lv_label_set_text(ui_IdleQuote,"I MEAOW YOU!");
// lv_obj_set_style_text_color(ui_IdleQuote, lv_color_hex(0x9D9D9D), LV_PART_MAIN | LV_STATE_DEFAULT );
// lv_obj_set_style_text_opa(ui_IdleQuote, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_text_letter_space(ui_IdleQuote, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_text_line_space(ui_IdleQuote, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_text_align(ui_IdleQuote, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_text_font(ui_IdleQuote, &ui_font_SGK100h16, LV_PART_MAIN| LV_STATE_DEFAULT);

// }
