#!/usr/bin/env python3
"""The CLOCK app's city list for the companion (src/tzdata.ts): each city's name on the knob and
the POSIX rule it follows, from this computer's zoneinfo, checked against the coming year the way
the Mac service checks LOCAL (NanoDepsidf/tools/quadra.py zone_rule). Run after a tzdata update:
    python3 companion/scripts/gen_tzdata.py"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "NanoDepsidf", "tools"))
import quadra  # noqa: E402

CITIES = """Pacific/Honolulu America/Anchorage America/Los_Angeles America/Vancouver America/Denver
America/Phoenix America/Chicago America/Mexico_City America/New_York America/Toronto America/Bogota
America/Lima America/Santiago America/Halifax America/St_Johns America/Sao_Paulo
America/Argentina/Buenos_Aires Atlantic/Reykjavik Europe/London Europe/Dublin Europe/Lisbon
Africa/Lagos Europe/Paris Europe/Berlin Europe/Madrid Europe/Rome Europe/Amsterdam Europe/Zurich
Europe/Stockholm Europe/Warsaw Europe/Prague Europe/Athens Europe/Helsinki Europe/Kyiv
Europe/Istanbul Africa/Cairo Africa/Johannesburg Africa/Nairobi Asia/Jerusalem Asia/Beirut
Europe/Moscow Asia/Riyadh Asia/Dubai Asia/Tehran Asia/Karachi Asia/Kolkata Asia/Kathmandu
Asia/Dhaka Asia/Bangkok Asia/Jakarta Asia/Singapore Asia/Hong_Kong Asia/Shanghai Asia/Taipei
Asia/Manila Asia/Seoul Asia/Tokyo Australia/Perth Australia/Adelaide Australia/Brisbane
Australia/Sydney Australia/Melbourne Pacific/Auckland Pacific/Chatham Etc/UTC""".split()

rows = []
for zone in CITIES:
    city = zone.rsplit("/", 1)[-1].replace("_", " ")
    rows.append(f'  {{ city: "{city}", label: "{quadra.zone_label(zone)}", zone: "{zone}", rule: "{quadra.zone_rule(zone)}" }},')
version = open(os.path.join(quadra.ZONEINFO, "+VERSION")).read().strip() if os.path.exists(os.path.join(quadra.ZONEINFO, "+VERSION")) else "?"
out = os.path.join(HERE, "..", "src", "tzdata.ts")
with open(out, "w") as f:
    f.write(f"""// GENERATED by scripts/gen_tzdata.py from zoneinfo (tzdata {version}) -- do not edit by hand.
// The CLOCK app's cities: the name the knob shows (12 characters) and the POSIX rule it follows.
export interface City {{ city: string; label: string; zone: string; rule: string }}
export const CITIES: City[] = [
""" + "\n".join(rows) + "\n];\n")
print(f"wrote {out}: {len(rows)} cities (tzdata {version})")
