// Silkscreen (OFL license, google/fonts ofl/silkscreen), ASCII 0x20-0x7E, 1bpp -- true
// monochrome pixel-art font, no anti-aliasing. LovyanGFX GFXfont format, repacked
// pixel-for-pixel from the earlier LVGL conversion (data in ui_font_silkscreen.cpp).
//
// Regular weight only, used everywhere: 16px for the main screen + menu rows, 8px for the
// Main Screen's F1/F3/F4 cheat-sheet tags. A bold 16px weight for the selected menu row was
// tried twice and rejected on hardware both times -- keep weight uniform.
#pragma once

#include <LovyanGFX.hpp>

extern const lgfx::GFXfont ui_font_silkscreen_16_regular; // line height 18px
extern const lgfx::GFXfont ui_font_silkscreen_8_regular;  // line height 9px
// 10px: generated by tools/gen_silkscreen_font.py -- the Pixel UI's small text. Built from the
// 8px glyphs with cap rows 1 and 3 doubled (5 -> 7 rows), so every stroke stays exactly 1px.
// 12px (FreeType mono, mixed 1/2px strokes) read too big on hardware, 8px too small, and a
// straight FreeType 10px render leaves gaps in letters like S.
extern const lgfx::GFXfont ui_font_silkscreen_10_regular; // caps 7px, line height 12px
