

#pragma once


#include "haptic.h"
#include <ArduinoJSON.h>


#define MAX_PROFILES 10




class HapticProfile {
public:
    HapticProfile();
    ~HapticProfile();

    HapticProfile& operator=(JsonObject& obj);

    uint32_t profile_id; // unique id generated by frontend
    String profile_name; // TODO max 20 characters
    String profile_desc; // TODO max 50 characters
    hapticConfig config;
    hapticParms parms;   // TODO it seems the hapticParams are not used in the haptic module... dead code should be removed.

    /* 
        Maybe worth to consider to have profile_name and profile_display_name.
        Its possible that user might want to keep different profile name in profile list and display different name in nano GUI.
        RU: I don't think so. Sounds like an unnecessary complication.
    */

};



class HapticProfileManager {
public:
    HapticProfileManager();
    ~HapticProfileManager();

    HapticProfile* add(String name);
    HapticProfile* operator[](String name);
    HapticProfile* get(String name);
    void remove(String name);
    int size();

    void fromSPIFFS();
    void toSPIFFS();
protected:
    HapticProfile profiles[MAX_PROFILES];
};